---
title: "TBD"
subtitle: "TBD"
author: "TBD"
thanks: "Code and data are available at: LINK."
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
output:
  bookdown::pdf_document2:
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(kableExtra)
library(janitor)
library(dplyr)
library(palettetown)
library(wesanderson)
library(RColorBrewer)
library(ggthemes)
library(scales)
library(broom)

all_simulated_dataset <- 
  readr::read_csv("../../inputs/data/simulated_data.csv")
```

```{r, echo = FALSE, include=FALSE, message = FALSE}
#### Global Functions ####
percent <- function(x, decimal = 2, format = "f") {   
  paste0(formatC(x, format = format, digits = decimal), "%")
}
```

# Data

```{r regions, echo = FALSE, message = FALSE}
#### Pie Chart ####
### Import cleaned business licences dataset
dfCleanBiz <- readr::read_csv("../../inputs/data/clean_business_licences.csv")
### Create data frame
dfBoroughs <- data.frame(
  group = dfCleanBiz$fsa,
  value = dfCleanBiz$n
)
### Calculate percentages
dfBoroughs <- dfBoroughs %>% 
  arrange(desc(group)) %>%
  mutate(prop = value / sum(dfBoroughs$value) *100) %>%
  mutate(ypos = cumsum(prop)- 0.5*prop ) %>%
  arrange(desc(prop))
dfBoroughs <- dfBoroughs[-c(10),]
# print(dfBoroughs)

### Create pie chart
ggplot(dfBoroughs, aes(x="", y = prop, fill = group)) +
  geom_bar(stat = "identity", width = 1, color = "black") +
  coord_polar("y", start = 0) +
  theme_void() +
  geom_text(aes(x=1.65, y = ypos, label = percent(prop)), color = "black", size=2.8) +
  scale_fill_brewer(palette = "Set3") + 
  labs(fill = "Region", title = "Proportion of Restaurants in Toronto by Borough") +
  theme(plot.title = element_text(face = "bold"))
```

```{r Q1, echo = FALSE, message=FALSE}
ggplot(data = all_simulated_dataset, mapping = aes (x = Q1, fill = type)) +
  geom_bar() + coord_flip() +
  theme_fivethirtyeight() +
  scale_fill_tableau(labels = c("Control", "Intervention"), guide = guide_legend(reverse = TRUE)) +
  labs(fill = "Condition", title = "Q1")
```


```{r Q2, echo = FALSE, message = FALSE}
### "What best describes the scale of your restaurant?
### Small (full seating capacity is under 30)
### Medium (full seating capacity between 30 and 60)
### Large (full seating capacity is 60+) "
ggplot(data = all_simulated_dataset, mapping = aes (x = Q2, fill = type)) +
    geom_bar() +
  scale_x_discrete(limit = c ("Small", "Medium", "Large")) +
  labs(x = "Scale of Restaurant",
       y = "# of Restaurants",
       title = "Q2") +
  labs(fill = "Condition", title = "Q2") +
  theme_fivethirtyeight() +
  scale_fill_tableau(labels = c("Control", "Intervention"), guide = guide_legend(reverse = TRUE))
```

```{r Q3, echo = FALSE, message = FALSE}
### What best describes your restaurant segmentation?
### Fast-food/quick service
### Casual Dining
### Fine Dining
### Other
ggplot(data = all_simulated_dataset, mapping = aes (x = Q3, fill = type)) +
  geom_bar() +
  scale_x_discrete(limit = c ("Fine Dining", "Casual Dining", "Fast-food/quick service", "Other")) +
  labs(x = "Type of Restaurant",
       y = "# of Restaurants",
       title = "Q3") +
  theme_fivethirtyeight() +
  scale_fill_tableau(labels = c("Control", "Intervention"), guide = guide_legend(reverse = TRUE))
```

```{r Q4, echo = FALSE, message = FALSE}
### How many years has your restaurant been in operation?
### 1-4 years
### 5-7 years
### 8-10 years
### 10 or more years
ggplot(data = all_simulated_dataset, mapping = aes (x = Q4, fill = type)) +
  geom_bar() + coord_flip() +
  scale_x_discrete(limit = c ("1-4 years", "5-7 years", "8-10 years", "10 or more years")) +
  labs(x = "Years of Operation",
       y = "# of Restaurants",
       title = "Q4") +
  theme_fivethirtyeight() +
  scale_fill_tableau(labels = c("Control", "Intervention"), guide = guide_legend(reverse = TRUE))
```

```{r Q5 + Q6 Table, echo = FALSE, message = FALSE}
### Prior to (intervention start date), how many people did you employ?
### How many people do you currently employ?

t1 <-
all_simulated_dataset %>%
  group_by(type) %>%
  summarise(prior_employees = mean(Q5, na.rm = TRUE, .groups = NULL))

t2 <-
all_simulated_dataset %>%
  group_by(type) %>%
  summarise(curr_employees = mean(Q6, na.rm = TRUE), .groups = NULL)

total <- merge(t1, t2, by = c("type"))


kable(total,
      col.names = c("Intervention Group",
                  "# of Employees Prior to Intervention",
                  "Current # of Employees")) %>%
      footnote(general = "Change in # of employees before and after intervention period (Q5 + Q6)") %>%
  kable_paper(c("striped", "hover"))
```

```{r Q7, echo = FALSE, message = FALSE}
### Between (start date of intervention) and (end date of intervention) was your total sales revenue higher, lower, or about the same as it was ### during the same length of time last month.**
### Higher
### Lower
### Around the Same

ggplot(data = all_simulated_dataset, mapping = aes(x = Q7, fill = type)) + 
  geom_bar() +
  labs(x = "Did revenue increase, decrease, or remain the same compared to last month?",
       y = "# of restaurants",
       title = "Q7",
       fill = "Type") +
  theme_fivethirtyeight() + 
  scale_fill_tableau(labels = c("Control", "Intervention"), guide = guide_legend(reverse = TRUE))
```

```{r Q8, echo = FALSE, message = FALSE}
### What was the approximate percentage decrease in total sales revenue between (start date of intervention) and (end date of intervention) 
### compared to the same time period last year. **
### Decline of 50% or more
### Decline of 25% to 50%
### Decline of 10% to 25%
### Decline of 10% or less

ggplot(data = all_simulated_dataset, mapping = aes (x = Q8, fill = type)) +
  geom_bar(position = "stack") + coord_flip() +
  scale_x_discrete(limit = c("Decline of 50% or more", "Decline of 25% to 50%", "Decline of 10% to 25%", "Decline of 10% or less")) + 
  labs(x = "Aprrox. Decrease in Total Sales Revenue",
       y = "# of Restaurants",
       title = "Q8",
       fill = "Type") +
  theme_fivethirtyeight() + 
  scale_fill_tableau(labels = c("Control", "Intervention"), guide = guide_legend(reverse = TRUE))
```

```{r Q9, echo = FALSE, message = FALSE}
### Before the (intervention start date), approximately how much of your total monthly sales revenue came from takeout or delivery?
### Did not offer takeout or delivery
### 25% or less
### 25- 50%
### 50-75%
### 75% or more

ggplot(data = all_simulated_dataset, mapping = aes (x = Q9, fill = type)) +
  geom_bar(position = "stack") +  coord_flip() + 
  scale_x_discrete(limit = c("Did not offer takeout or delivery", "25% or less", "25-50%", "50-75%", "75% or more")) + 
  labs(x = "Total Monthly Sales Revenue Fromt Takeout or Delivery",
       y = "# of Restaurants",
       title = "Q9",
       fill = "Legend") +
  theme_fivethirtyeight() + 
  scale_fill_tableau(labels = c("Control", "Intervention"), guide = guide_legend(reverse = TRUE))
```

```{r Q10, echo = FALSE, message = FALSE}
### Between (start date of intervention) and (end date of intervention), did you make any adjustments to your menu prices?
### Yes, prices were raised
### Yes, prices were lowered
### No changes were made

ggplot(data = all_simulated_dataset, mapping = aes (x = Q10, fill = type)) +
  geom_bar() +  
  coord_flip() + 
  scale_x_discrete(limit = c("Yes, prices were raised", "Yes, prices were lowered", "No changes were made")) + 
  labs(x = "Adjustments to Menu Prices",
       y = "# of Restaurants",
       title = "Q10",
       fill = "Legend") +
  scale_fill_tableau(labels = c("Control", "Intervention"), guide = guide_legend(reverse = TRUE)) +
  theme_fivethirtyeight()
```


```{r Q11, echo = FALSE, message = FALSE}
### Between (start date of intervention) and (end date of intervention), which food courier service did you receive the most orders from?
### UberEats
### SkiptheDishes 
### DoorDash
### Other
### In-house delivery service
### None

ggplot(data = all_simulated_dataset, mapping = aes(x = Q11, fill = type)) +
  geom_bar(position = "stack") + coord_flip() +
  scale_x_discrete(limit = c("UberEats", "SkiptheDishes", "DoorDash", "Other", "In-house delivery service", "None")) +
  labs(x = "Delivery Service",
       y = "# of Restaurants",
       title = "Q11",
       fill = "Legend") +
  scale_fill_tableau(labels = c("Control", "Intervention"), guide = guide_legend(reverse = TRUE)) + 
  theme_fivethirtyeight()
```


```{r Q12, echo = FALSE, message = FALSE}
### Between (start date of intervention) and (end date of intervention) did you reduce your ### restaurant’s hours of operation?
### Yes
### No

ggplot(data = all_simulated_dataset, mapping = aes(x = Q12, fill = type)) +
  geom_bar(position = position_dodge(1)) +
  labs(x = "Was there a reduction in restaurant hours?",
       y = "# of restaurants",
       title = "Q12",
       fill = "Legend") +
  theme_fivethirtyeight() +
  scale_fill_tableau(labels = c("Control", "Intervention"), guide = guide_legend(reverse = TRUE))
```

```{r Q13, echo = FALSE, message = FALSE}
### If yes, approximately how many hours per week did you reduce by
### 15% or less
### 15-30%
### 30-50%
### 50-75%
### 75% or more

ggplot(data = all_simulated_dataset, mapping = aes(x = Q13, fill = type)) +
  geom_bar(position = "stack") +
  labs(x = "Hours Reduced per Week",
       y = "# of Restaurants",
       title = "Q13",
       fill = "Legend") +
  scale_fill_tableau(labels = c("Control", "Intervention"), guide = guide_legend(reverse = TRUE)) +
  theme_fivethirtyeight()
```


```{r Q14, echo = FALSE, message = FALSE}
### Between (start date of intervention) and (end date of intervention) did you reduce the 
### number of days your restaurant was open to the public?
### Yes
### No 

ggplot(data = all_simulated_dataset, mapping = aes(x = Q14, fill = type)) +
  geom_bar(position = position_dodge(1)) +
  labs(x = "Did you reduce the # of days you were open to the public between (start date) and (end date)?",
       y = "Y",
       title = "Q14",
       fill = "Legend") +
  scale_fill_tableau(labels = c("Control", "Intervention"), guide = guide_legend(reverse = TRUE)) +
  theme_fivethirtyeight()
```


```{r Q15, echo = FALSE, message = FALSE}
### If yes, how many days per week did you reduce by?
### 1-2 days
### 3-4 days
### 5-6 days
### 7 days
### Not Applicable

### bar graph/pie chart/line

ggplot(data = all_simulated_dataset, mapping = aes(x = Q15, fill = type)) +
  geom_bar(position = "stack") +
  labs(x = "How many days per week did you reduce by?",
       y = "# of restaurants",
       title = "Q15",
       fill = "Legend") +
    scale_fill_tableau(labels = c("Control", "Intervention"), guide = guide_legend(reverse = TRUE)) +
  theme_fivethirtyeight() 
```

## Statistical Tests

```{r statistical tests, echo = FALSE, message = FALSE}
### Welch's T-Test

# Q5
control_q5 <-
  all_simulated_dataset %>%
  filter(type == "Control") %>%
  select(Q5)
treatment_q5 <-
  all_simulated_dataset %>%
  filter(type == "Treated") %>%
  select(Q5)
tidy(t.test(control_q5, treatment_q5))



#Q6
control_q6 <-
  all_simulated_dataset %>%
  filter(type == "Control") %>%
  select(Q6)
treatment_q6 <-
  all_simulated_dataset %>%
  filter(type == "Treated") %>%
  select(Q6)
tidy(t.test(control_q6, treatment_q6))

### Paired T-Test

tidy(t.test(all_simulated_dataset$Q5,
       all_simulated_dataset$Q6,
       paired=TRUE,
       conf.level = 0.95))

# Chi-Square

#Q7

q7_chi <- table(all_simulated_dataset$Q7, all_simulated_dataset$type)
tidy(chisq.test((q7_chi)))

#Q8

q8_chi <- table(all_simulated_dataset$Q8, all_simulated_dataset$type)
tidy(chisq.test((q8_chi)))

#Q10

q10_chi <- table(all_simulated_dataset$Q10, all_simulated_dataset$type)
tidy(chisq.test((q10_chi)))

#Q12

q12_chi <- table(all_simulated_dataset$Q12, all_simulated_dataset$type)
tidy(chisq.test((q12_chi)))

#Q14

q14_chi <- table(all_simulated_dataset$Q14, all_simulated_dataset$type)
tidy(chisq.test((q14_chi)))
```

\newpage

# Appendix {-}

\newpage


# References